// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          int64
	Name        string
	Price       int32
	Description string
	Sellername  string
	Condition   bool
}

type Order struct {
	ID     int64
	Userid pgtype.Int8
	Bookid pgtype.Int8
}

type User struct {
	ID       int64
	Name     string
	Username string
	Email    string
	Password string
}
