// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import ()

type User struct {
	ID       int64
	Name     string
	Username string
	Email    string
	Password string
}
